version: '3'

interval: 5s

tasks:
  dev:
    deps:
      - task: up-dev
        silent: true
    sources:
      - go.mod
      - ./**/*.go
    cmds:
      - go mod tidy
      - go build -o app && ./app
      - defer: { task: cleanup }

  cleanup: killall -9 app || true

  up-dev:
    cmds:
      - docker compose up -d db
    
  build:
    cmds:
      - docker compose build

  up:
    deps:
      - task: build
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down